/// Flutter icons SleepIcons
/// Copyright (C) 2023 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  SleepIcons
///      fonts:
///       - asset: fonts/SleepIcons.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class SleepIcons {
  SleepIcons._();

  static const _kFontFam = 'SleepIcons';
  static const String? _kFontPkg = null;

  static const IconData os_iconwhitesvg = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData os_calendarwhitesvg = IconData(0xe806, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData os_log2whitesvg = IconData(0xe807, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData os_homewhitesvg = IconData(0xe808, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData os_resourceswhitesvg = IconData(0xe809, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData os_notif2svg = IconData(0xe80a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData os_remindsvg = IconData(0xe80c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
